import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { ClinicalTest, Consultation, Patient, Prescription, User, UserRole } from '../types';
const envUrl=(import.meta.env.VITE_SUPABASE_URL||(typeof process!=='undefined'?process.env?.SUPABASE_URL:'')||'') as string;
const envAnonKey=(import.meta.env.VITE_SUPABASE_ANON_KEY||(typeof process!=='undefined'?process.env?.SUPABASE_ANON_KEY:'')||'') as string;
let runtimeUrl=envUrl; let runtimeAnonKey=envAnonKey; let supabaseInstance:SupabaseClient|null=null;
export const supabaseConfig={getUrl:()=>runtimeUrl,getAnonKey:()=>runtimeAnonKey,isConfigured:()=>Boolean(runtimeUrl&&runtimeAnonKey&&runtimeUrl.startsWith('https://')),setCredentials:(url:string,key:string)=>{runtimeUrl=url.trim();runtimeAnonKey=key.trim();supabaseInstance=null;},clearCredentials:()=>{runtimeUrl=envUrl;runtimeAnonKey=envAnonKey;supabaseInstance=null;}};
export function getSupabase(){if(!supabaseConfig.isConfigured())return null;if(!supabaseInstance)supabaseInstance=createClient(runtimeUrl,runtimeAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return supabaseInstance;}
export async function testSupabaseConnection(){const c=getSupabase();if(!c)return{ok:false,message:'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in the deployment environment.'};try{const{error}=await c.from('pharmacy_users').select('id').limit(1);return error?{ok:false,message:`Supabase query error: ${error.message} (${error.code||'UNKNOWN'})`}:{ok:true,message:'Successfully connected to Supabase.'};}catch(e){return{ok:false,message:`Connection failed: ${e instanceof Error?e.message:String(e)}`};}}
export type RealtimeTable='medications'|'prescriptions'|'tests'|'patients'|'consultations'|'clinical_tests'|'sale_transactions'|'receipt_settings'|'pharmacy_users'|'audit_logs'; let activeChannel:ReturnType<SupabaseClient['channel']>|null=null;
export function subscribeToRealtimeChanges(tables:RealtimeTable[],onChange:(table:RealtimeTable)=>void){const c=getSupabase();if(!c)return()=>{};if(activeChannel){c.removeChannel(activeChannel);activeChannel=null;}let ch=c.channel('pharmapos-realtime-sync');for(const table of tables)ch=ch.on('postgres_changes' as any,{event:'*',schema:'public',table},(payload)=>onChange(table));ch.subscribe((status)=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')console.error(`Supabase Realtime subscription ${status}.`);});activeChannel=ch;return()=>{if(activeChannel){c.removeChannel(activeChannel);activeChannel=null;}};}
interface AuthResult{ok:boolean;user?:User;error?:string;}
function rowToUser(row:any):User{return{id:row.id,username:row.username,email:row.email||undefined,name:row.name,role:row.role as UserRole,status:row.status,createdAt:row.created_at,lastLogin:row.last_login||undefined,phone:row.phone||undefined,licenseNumber:row.license_number||undefined,avatarColor:row.avatar_color||'bg-teal-700'};}
export async function checkBootstrapAvailable(){return false;}
export async function signInWithSupabase(identifier:string,password:string):Promise<AuthResult>{const c=getSupabase();if(!c)return{ok:false,error:'Supabase is not configured. Please configure the deployment environment.'};const generic='Invalid credentials or user not authorized.';let email=identifier.trim();if(!email.includes('@')){const{data}=await c.from('pharmacy_users').select('email').ilike('username',identifier.trim()).maybeSingle();if(!data?.email)return{ok:false,error:generic};email=data.email;}const{data:a,error:ae}=await c.auth.signInWithPassword({email,password});if(ae||!a?.user)return{ok:false,error:generic};const{data:p,error:pe}=await c.from('pharmacy_users').select('*').eq('auth_user_id',a.user.id).maybeSingle();if(pe||!p){await c.auth.signOut();return{ok:false,error:'Account not fully set up. Please contact your administrator.'};}if(p.status!=='active'){await c.auth.signOut();return{ok:false,error:'This account has been deactivated. Please contact an Administrator.'};}const now=new Date().toISOString();void c.from('pharmacy_users').update({last_login:now}).eq('auth_user_id',a.user.id);return{ok:true,user:rowToUser({...p,last_login:now})};}
export async function getAuthenticatedProfile():Promise<User|null>{const c=getSupabase();if(!c)return null;const{data:s}=await c.auth.getSession();const au=s.session?.user;if(!au)return null;const{data:p}=await c.from('pharmacy_users').select('*').eq('auth_user_id',au.id).maybeSingle();if(!p||p.status!=='active'){await c.auth.signOut();return null;}return rowToUser(p);}
export function onSupabaseAuthStateChange(callback:(user:User|null)=>void){const c=getSupabase();if(!c)return()=>{};const{data}=c.auth.onAuthStateChange(async(_e,s)=>{if(!s?.user){callback(null);return;}setTimeout(async()=>callback(await getAuthenticatedProfile()),0);});return()=>data.subscription.unsubscribe();}
export async function signUpInitialAdmin():Promise<AuthResult>{return{ok:false,error:'Public account creation is disabled. An administrator must provision this account.'};}
export async function signOutSupabase(){const c=getSupabase();if(c)await c.auth.signOut();}
export async function listManagedUsers():Promise<{ok:boolean;users:User[];error?:string}>{const c=getSupabase();if(!c)return{ok:false,users:[],error:'Supabase is not configured.'};const{data,error}=await c.from('pharmacy_users').select('*').order('created_at',{ascending:true});if(error)return{ok:false,users:[],error:error.message};return{ok:true,users:(data||[]).map(rowToUser)};}
export interface AdminUserInput{name:string;username:string;email:string;phone?:string;role:UserRole;password:string;licenseNumber?:string;}
export interface AdminUserUpdate{name?:string;email?:string;phone?:string;role?:UserRole;licenseNumber?:string;}
async function invokeAdminUserFunction(body:Record<string,unknown>):Promise<{ok:boolean;user?:User;error?:string}>{const c=getSupabase();if(!c)return{ok:false,error:'Supabase is not configured.'};const{data,error}=await c.functions.invoke('admin-user-provisioning',{body});if(error)return{ok:false,error:error.message||'User-management request failed.'};if(!data?.ok)return{ok:false,error:data?.error||'User-management request failed.'};return{ok:true,user:data.user?rowToUser(data.user):undefined};}
export async function createManagedUser(input:AdminUserInput){return invokeAdminUserFunction({action:'create',...input});}
export async function updateManagedUser(userId:string,input:AdminUserUpdate){return invokeAdminUserFunction({action:'update',userId,...input});}
export async function setManagedUserStatus(userId:string,status:'active'|'inactive'){return invokeAdminUserFunction({action:'set_status',userId,status});}
export async function resetManagedUserPassword(userId:string,password:string){return invokeAdminUserFunction({action:'reset_password',userId,password});}
export async function deleteManagedUser(userId:string){return invokeAdminUserFunction({action:'delete',userId});}
function patientToRow(p:Patient){return{id:p.id,full_name:p.fullName,dob:p.dob,gender:p.gender,phone:p.phone,email:p.email||null,address:p.address||null,allergies:p.allergies||[],insurance_provider:p.insuranceProvider||null,insurance_policy_number:p.insurancePolicyNumber||null};}
export async function upsertPatientToSupabase(p:Patient){const c=getSupabase();if(!c)return false;const{error}=await c.from('patients').upsert(patientToRow(p));return!error;}
export async function insertConsultationToSupabase(x:Consultation){const c=getSupabase();if(!c)return false;const{error}=await c.from('consultations').insert({id:x.id,patient_id:x.patientId,patient_name:x.patientName,clinician_id:x.clinicianId,clinician_name:x.clinicianName,date:x.date,symptoms:x.symptoms,diagnosis:x.diagnosis,notes:x.notes||null,vitals:x.vitals||{}});return!error;}
export async function upsertClinicalTestToSupabase(x:ClinicalTest){const c=getSupabase();if(!c)return false;const{error}=await c.from('clinical_tests').upsert({id:x.id,consultation_id:x.consultationId||null,patient_id:x.patientId,patient_name:x.patientName||null,test_name:x.testName,category:x.category,status:x.status,results:x.results||null,reference_ranges:x.referenceRanges||null,notes:x.notes||null,requested_by:x.requestedBy,conducted_at:x.conductedAt||null});return!error;}
export async function upsertPrescriptionToSupabase(x:Prescription){const c=getSupabase();if(!c)return false;const{error}=await c.from('prescriptions').upsert({id:x.id,rx_number:x.rxNumber,barcode:x.barcode,patient_name:x.patientName,patient_dob:x.patientDOB,patient_phone:x.patientPhone,doctor_name:x.doctorName,doctor_license:x.doctorLicense,doctor_clinic:x.doctorClinic,medication_id:x.medicationId||null,medication_name:x.medicationName,dosage_instructions:x.dosageInstructions||'',quantity_prescribed:x.quantityPrescribed||0,quantity_dispensed_so_far:x.quantityDispensedSoFar||0,refills_allowed:x.refillsAllowed||0,refills_remaining:x.refillsRemaining||0,date_issued:x.dateIssued,expiry_date:x.expiryDate,status:x.status,insurance_provider:x.insuranceProvider||null,insurance_co_pay_rate:x.insuranceCoPayRate||0});return!error;}
